name: Hata Bildirimi
description: Hata raporla
labels: ["bug"]
body:
  - type: textarea
    id: screenshot
    attributes:
      label: Hata ekranı
      description: Hata aldığınız andaki ekran görüntüsü nedir?
      placeholder: Ekran görüntüsünü kopyala/yapıştır yapın.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Sürüm bilgisi
      description: Deponun hangi sürümünü kullanıyorsunuz?
      placeholder: |
        - git rev-parse HEAD
      render: text
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Ayrıntılar
      description: Eklemek istediğiniz bir açıklama var mı?
      placeholder: Ek açıklamalar
